function dxdt=call_nolinealPro(t,x) %% no Lineal Promedio

global Gdc Gac Rf Lf Rl Ll Cdc Vrms

%entrada
md = md0 + 0.4*md0*(t>=0)

%% perturbacion (red electrica)
ipv = ipv0*(t>=0)
%%
%Espacio de estados
dxdt = [1/Cdc*(ipv-Gdc(ma*x(2)+ma*x(3)+ma*x(4)));...
        1/Lf*(Gac*ma*x(1)-Rf*x(2)-Vas);...
        1/Lf*(Gac*ma*x(1)-Rf*x(3)-Vbs);...
        1/Lf*(Gac*ma*x(1)-Rf*x(4)-Vcs);...
        1/Ll*(vas-x(5));...
        1/Ll*(vas-x(6));...
        1/Ll*(vas-x(7))]; 